Repository mrdoob/three.js, pull requests merged in 2024-11, with the labels that each got.

#29867 WebGPURenderer: Fix OffscreenCanvas Support in WebGL
  src/renderers/webgl-fallback/utils/WebGLTextureUtils.js
Labels: WebGL Backend

#29959 PMREMGenerator: Add optional `renderTarget` in `fromScene()`
  src/renderers/common/extras/PMREMGenerator.js
Labels: WebGPU

#29984 Docs: Add JSDoc config and improve `Node` docs.
  .gitignore
  package-lock.json
  package.json
  src/nodes/core/Node.js
  src/nodes/core/constants.js
  src/nodes/display/ColorAdjustment.js
  src/nodes/functions/material/getAlphaHashThreshold.js
  src/nodes/utils/PostProcessingUtils.js
  utils/docs/jsdoc.config.json
Labels: Documentation
